/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoCG;


import com.jogamp.opengl.GL2;
import com.jogamp.opengl.GLCapabilities;

import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.awt.GLCanvas;


/**
 *
 * @author jason
 */
public class Window extends javax.swing.JFrame{
    GLCapabilities capabilities;
    int valorx, valory, i = 0;
    SistemaDeCoordenadas converte = new SistemaDeCoordenadas();
    float[] ArrayCoord= new float[3];
    boolean clicked = false;
    /**
     * Creates new form exemplo02
     */
    public Window() {
              //getting the capabilities object of GL2 profile        
      final GLProfile profile = GLProfile.get(GLProfile.GL2);
      capabilities = new GLCapabilities(profile);
       
      initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gLCanvas = new GLCanvas (capabilities);
        lblY = new javax.swing.JLabel();
        lblNdcx = new javax.swing.JLabel();
        lblNdcy = new javax.swing.JLabel();
        lblDcy = new javax.swing.JLabel();
        lblDcx = new javax.swing.JLabel();
        CoordenadaX = new javax.swing.JLabel();
        CoordenandaY = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Coord1 = new javax.swing.JFormattedTextField();
        Coord2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setaX = new javax.swing.JLabel();
        RemoverCoordenadas = new javax.swing.JButton();
        setaY = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListX = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListY = new javax.swing.JList<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Camputação Gráfica");
        setBackground(new java.awt.Color(160, 154, 238));

        gLCanvas.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        gLCanvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gLCanvasMouseClicked(evt);
            }
        });
        gLCanvas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                gLCanvasMouseMoved(evt);
            }
        });

        lblY.setText("0,000");

        lblNdcx.setText("0,000");

        lblNdcy.setText("0,000");

        lblDcy.setText("0,000");

        lblDcx.setText("0,000");

        CoordenadaX.setText("Coordenada X:");

        CoordenandaY.setText("Coordenada Y:");

        jLabel2.setText("Coordenada NDCX:");

        jLabel3.setText("Coordenada DCX:");

        jLabel4.setText("Coordenada NDCY:");

        jLabel6.setText("Coordenada DCY:");

        lblX.setText("0,000");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(114, 109, 109), null));

        Coord1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        Coord1.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N

        Coord2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        Coord2.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        jLabel1.setText("Coord. X");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        jLabel5.setText("Coord. Y");

        setaX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seta2.png"))); // NOI18N

        RemoverCoordenadas.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        RemoverCoordenadas.setText("Remover");
        RemoverCoordenadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverCoordenadasActionPerformed(evt);
            }
        });

        setaY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seta2.png"))); // NOI18N

        jScrollPane1.setViewportView(jListX);

        jScrollPane2.setViewportView(jListY);

        jComboBox1.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pixel", "Reta", "Circunferência", "Triângulo" }));

        jButton1.setFont(new java.awt.Font("Serif", 1, 15)); // NOI18N
        jButton1.setText("Visualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Coord1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(setaX))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(setaY))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Coord2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(RemoverCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Coord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Coord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(setaX, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(setaY, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(RemoverCoordenadas)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CoordenadaX)
                            .addComponent(CoordenandaY))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblX, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNdcx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNdcy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDcx)
                            .addComponent(lblDcy)))
                    .addComponent(gLCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDcx)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblDcy)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNdcx)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblNdcy)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblY))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CoordenadaX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CoordenandaY)))
                        .addGap(38, 38, 38)
                        .addComponent(gLCanvas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblY.getAccessibleContext().setAccessibleName("0,000");
        lblY.getAccessibleContext().setAccessibleDescription("");
        lblNdcx.getAccessibleContext().setAccessibleName("0,000");
        lblNdcx.getAccessibleContext().setAccessibleDescription("");
        lblNdcy.getAccessibleContext().setAccessibleName("0,000");
        lblNdcy.getAccessibleContext().setAccessibleDescription("");
        lblDcy.getAccessibleContext().setAccessibleName("0,000");
        lblDcy.getAccessibleContext().setAccessibleDescription("");
        lblDcx.getAccessibleContext().setAccessibleName("0,000");
        lblDcx.getAccessibleContext().setAccessibleDescription("");
        lblX.getAccessibleContext().setAccessibleName("0,000");
        lblX.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciaComponentes(){
        
    } 
    
    private void gLCanvasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gLCanvasMouseMoved
                valorx = posicionaNoPlanoX(evt.getX());
                valory = posicionaNoPlanoY(evt.getY());
                lblX.setText(Integer.toString(valorx));
                lblY.setText(Integer.toString(valory));
                lblNdcx.setText(String.format("%.3f", (converte.paraNDCX(valorx))));
                lblNdcy.setText(String.format("%.3f", (converte.paraNDCY(valory))));
                lblDcx.setText(Integer.toString(converte.paraNCX()));
                lblDcy.setText(Integer.toString(converte.paraNCY()));
    }//GEN-LAST:event_gLCanvasMouseMoved

    private void gLCanvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gLCanvasMouseClicked
      ArrayCoord[i] = (float) converte.paraNDCX(evt.getX());
      i++;
      ArrayCoord[i] = (float) converte.paraNDCY(evt.getY());
      i++;
      ArrayCoord[i] = 0;
      i = 0;
      clicked = true;
    }//GEN-LAST:event_gLCanvasMouseClicked

    private void RemoverCoordenadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverCoordenadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemoverCoordenadasActionPerformed
    
    public float[] repassaCoordenadas(){
        clicked = false;
        return ArrayCoord;
    }
       
    
    
    public void iniciaPlanoXY(GL2 gl){
      //plano X
      gl.glBegin (GL2.GL_LINES);
      gl.glVertex3f(1f,0, 0);
      gl.glVertex3f(-1f,0, 0);
      gl.glEnd();
      //plano Y
      gl.glBegin (GL2.GL_LINES);
      gl.glVertex3f(0,-1f, 0);
      gl.glVertex3f(0, 1f, 0);
      gl.glEnd();
    }

 public static int posicionaNoPlanoX(int x) {
        return x - 250;
    }

    public static int posicionaNoPlanoY(int y) {
     
        return 250 - y;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Coord1;
    private javax.swing.JFormattedTextField Coord2;
    private javax.swing.JLabel CoordenadaX;
    private javax.swing.JLabel CoordenandaY;
    private javax.swing.JButton RemoverCoordenadas;
    protected com.jogamp.opengl.awt.GLCanvas gLCanvas;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListX;
    private javax.swing.JList<String> jListY;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDcx;
    private javax.swing.JLabel lblDcy;
    private javax.swing.JLabel lblNdcx;
    private javax.swing.JLabel lblNdcy;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JLabel setaX;
    private javax.swing.JLabel setaY;
    // End of variables declaration//GEN-END:variables
}
